permissions:
  contents: write

name: Release Extension

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Validate tag format
        run: |
          if [[ ! "${GITHUB_REF_NAME}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Tag must match vX.Y.Z"
            exit 1
          fi

      - name: Extract version from tag
        id: version
        run: echo "version=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT

      - name: Update manifest.json version
        run: |
          jq --arg v "${{ steps.version.outputs.version }}" '.version = $v' manifest.json > manifest.tmp.json
          mv manifest.tmp.json manifest.json

      - name: Build extension (rollup)
        run: npx rollup -c

      - name: Create zip for release
        run: |
          cd dist && zip -r ../extension.zip .

      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: extension-zip
          path: extension.zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ steps.version.outputs.version }}
          tag_name: ${{ github.ref_name }}
          files: extension.zip
